
name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - run: docker build -t ghcr.io/programming-framework/python-app:latest .
      - run: docker push  ghcr.io/programming-framework/python-app:latest 

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    -  name: Login to Docker Hub
       uses: docker/login-action@v3
       with:
         registry: ghcr.io
         username: ${{ github.actor }}
         password: ${{ secrets.GITHUB_TOKEN }}

    - run: docker pull
